#!/bin/bash


menuLogo(){
  echo █████████████████████████████▀█████████████████████████████
  echo █─▄▄▄─█─█─██▀▄─██▄─▀█▄─▄█─▄▄▄▄█▄─▄▄─███▄─▄▄▀█▄─▀█▄─▄█─▄▄▄▄█
  echo █─███▀█─▄─██─▀─███─█▄▀─██─██▄─██─▄█▀████─██─██─█▄▀─██▄▄▄▄─█
  echo ▀▄▄▄▄▄▀▄▀▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▀▀▄▄▄▄▀▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀
  echo -e '\n'
}


menuOptions(){
  echo 1: View My DNS
  echo 2: Change DNS
  echo 3: Select DNS from Database
  echo 4: Reset DNS
  echo -e "5: Exit\n"
}


getMenuNum(){
  local Num
  read -p "Enter the option: " Num
  echo ${Num}
}


dns_changer() {

   sudo cp /etc/resolv.conf /etc/resolv.con.backup

  read -p "Enter DNS IP1: " dns1
  read -p "Enter DNS IP2: " dns2

  if [[ $dns1 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]] &&
     [[ -z "$dns2" || $dns2 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then

    echo -e "\n\nSetting DNS:\n"
    echo "# Generated by NetworkManager" | sudo tee /etc/resolv.conf
    echo nameserver $dns1 | sudo tee -a /etc/resolv.conf
    if [[ ! -z "$dns2" && "$dns2" != " " ]]; then
      echo nameserver $dns2 | sudo tee -a /etc/resolv.conf
    fi
    echo -e "\nDNS successfully updated."
  else
    echo -e "\nInvalid DNS IP entered."
  fi
}


viewMyDns(){
  echo -e "\nYour Current DNS Configuration:\n"
  sudo cat /etc/resolv.conf
  echo -e "\n"
}


SelectDnsFromDatabase(){
  local dns_file="./database/DnsDatabse.txt"
  sudo cp /etc/resolv.conf /etc/resolv.con.backup
  if [[ ! -f "$dns_file" ]]; then
    echo "Error: DNS database file not found."
    return 1
  fi

  echo "Available DNS servers:"
  cut -d ':' -f 1 "$dns_file"

  echo -e "\n"
  read -p "Enter DNS server name: " selected_dns

  if grep -q "^$selected_dns:" "$dns_file"; then
    local selected_ips=$(grep "^$selected_dns:" "$dns_file" | cut -d ':' -f2-)
    local ip1=$(echo "$selected_ips" | cut -d ':' -f1)
    local ip2=$(echo "$selected_ips" | cut -d ':' -f2)

    echo -e "\n\nSetting DNS:\n"
    echo "# Generated by NetworkManager" | sudo tee /etc/resolv.conf
    echo "nameserver $ip1" | sudo tee -a /etc/resolv.conf
    if [[ ! -z "$ip2" && "$ip2" != " " ]]; then
      echo "nameserver $ip2" | sudo tee -a /etc/resolv.conf
    fi
    echo -e "\nDNS successfully updated from database."
  else
    echo "Error: Selected DNS server not found in the database."
  fi
}


resetDns(){
  local backup_file="/etc/resolv.con.backup"
  local output_file="/etc/resolv.conf"
  if [[ ! -f "$backup_file" ]]; then
    echo "Error: Backup file not found. Cannot reset DNS."
    return 1
  fi

  sudo cp "$backup_file" "$output_file"

  echo "DNS reset to the backup configuration."
}
