#!/bin/bash

menu(){

echo █████████████████████████████▀█████████████████████████████
echo █─▄▄▄─█─█─██▀▄─██▄─▀█▄─▄█─▄▄▄▄█▄─▄▄─███▄─▄▄▀█▄─▀█▄─▄█─▄▄▄▄█
echo █─███▀█─▄─██─▀─███─█▄▀─██─██▄─██─▄█▀████─██─██─█▄▀─██▄▄▄▄─█
echo ▀▄▄▄▄▄▀▄▀▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▀▀▄▄▄▄▀▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀
echo -e '\n'

}


dns_changer() {
sudo cp /etc/resolv.conf /etc/resolv.con.backup


read -p "Enter Dns Ip1: " dns1
read -p "Enter Dns Ip2: " dns2

if  [[ $dns1 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]] &&  [[ $dns2 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then

echo -e "\n\nDns:\n"
echo "# Generated by NetworkManager" | sudo tee /etc/resolv.conf
echo nameserver $dns1 | sudo tee -a /etc/resolv.conf
echo nameserver $dns2 | sudo tee -a  /etc/resolv.conf
if [[ $? -eq 0 ]]; then

echo -e "\nsuccess"

else

echo -e "\nNot Success"

fi

else
  echo -e "\n Not valid Dns"
fi

}
